from pyray import BLACK

WINDOW_WIDTH = 1220
WINDOW_HEIGHT = 680
BG_COLOR = BLACK
PLAYER_SPEED = 7
LASER_SPEED = 9
METEOR_SPEED_RANGE = [3, 4]
METEOR_TIMER_DURATION = 0.4
FONT_SIZE = 60
FONT_PADDING = 60
